"""Add user authentication

Revision ID: fd21c9f10b3d
Revises:
Create Date: 2025-11-09 14:44:24.466554

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime
from werkzeug.security import generate_password_hash


# revision identifiers, used by Alembic.
revision = 'fd21c9f10b3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Create users table
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('verification_token')
    )

    # Add user_id column as nullable first (to preserve existing data)
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # Create a default user for existing boards
    connection = op.get_bind()
    users_table = sa.table('users',
        sa.column('id', sa.Integer),
        sa.column('username', sa.String),
        sa.column('email', sa.String),
        sa.column('password_hash', sa.String),
        sa.column('is_verified', sa.Boolean),
        sa.column('created_at', sa.DateTime)
    )

    # Insert default user
    connection.execute(
        users_table.insert().values(
            username='admin',
            email='admin@kanban.local',
            password_hash=generate_password_hash('admin123'),
            is_verified=True,
            created_at=datetime.utcnow()
        )
    )

    # Get the default user's ID
    result = connection.execute(sa.text("SELECT id FROM users WHERE username='admin'"))
    default_user_id = result.fetchone()[0]

    # Assign all existing boards to the default user
    connection.execute(
        sa.text(f"UPDATE boards SET user_id = {default_user_id} WHERE user_id IS NULL")
    )

    # Now make user_id NOT NULL and add foreign key
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.alter_column('user_id', nullable=False)
        batch_op.create_foreign_key('fk_boards_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    op.drop_table('users')
    # ### end Alembic commands ###
